name: Hydra Runner

on:
  workflow_dispatch: {}          
  repository_dispatch: {}        

jobs:
  build-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build Docker
        run: docker build -t hydra-core:latest .

      - name: Run Orchestrator
        # run: docker run --rm hydra-core:latest
        run: docker run --rm -v $(pwd)/data:/app/data hydra-core

